apps/blog/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/4/17 13:57
# @Author  : Hezq
# @Contact : Hezq168@gmail.com
# @File    : urls.py
# @Project : mysite
# @Software: PyCharm


from django.urls import path
from blog import views as blog_views

urlpatterns = [
    # 博客首页
    path('', blog_views.index, name='blog_index'),
    # 博客文章页
    path('post/<int:id>', blog_views.post, name='blog_post'),
    # 博客类别
    path('category/<int:_id>', blog_views.Category.as_view(), name='blog_category'),
    # 博客标签
    path('tag/<int:_id>', blog_views.TagView.as_view(), name='blog_tag'),
    # 博客公告
    path('notice/<int:_id>', blog_views.NoticeView.as_view(), name='blog_notice'),
    # 博客评论
    path('comment', blog_views.CommentView.as_view(), name='blog_comment'),
    # 博客关注
    path('stars', blog_views.StarsView.as_view(), name='blog_stars')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    # 用户
    path('users/', include('users.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from users.models import UserProfile
import django.utils.timezone as timezone


# 博客分类
class Type(models.Model):
    name = models.CharField(max_length=16, verbose_name='分类')
    keywords = models.CharField(max_length=32, verbose_name='关键字', null=True)
    description = models.CharField(max_length=64, verbose_name='描述', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = "博客分类"


# 博客标签
class Tag(models.Model):
    name = models.CharField('标签', max_length=32)
    keywords = models.CharField(max_length=32, verbose_name='关键字', null=True)
    description = models.CharField(max_length=64, verbose_name='描述', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = "博客标签"


# 博客文章
class Post(models.Model):
    title = models.CharField(max_length=32, verbose_name='标题')
    # 博客分类 一对多
    type = models.ForeignKey(Type, on_delete=models.DO_NOTHING, verbose_name='分类')
    content = RichTextUploadingField(verbose_name='内容')
    author = models.ForeignKey(UserProfile, on_delete=models.DO_NOTHING, verbose_name='作者')
    page_view = models.IntegerField(verbose_name='阅读数', default=0)
    cover = models.ImageField('封面', default='cover/default.jpg', upload_to='cover/%Y/%m/%d')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    updated_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    # 博客标签 多对多关系
    tag = models.ManyToManyField(Tag, verbose_name='标签')
    keywords = models.CharField(max_length=32, verbose_name='关键字', null=True)
    description = models.CharField(max_length=64, verbose_name='描述', null=True)

    def __str__(self):
        return '<Blog: %s>' % self.title

    class Meta:
        verbose_name = "博客文章"
        verbose_name_plural = "博客文章"
        ordering = ['-id']


# 博客评论
class Comments(models.Model):
    content = RichTextUploadingField(verbose_name='评论内容', config_name='default')
    # 多对一
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING, verbose_name='博客文章')
    created_time = models.DateTimeField(default=timezone.now, verbose_name='评论时间')
    blog_user = models.ForeignKey(UserProfile, on_delete=models.DO_NOTHING, verbose_name='评论用户', default=1)
    is_reply = models.IntegerField(verbose_name='回复', default=0)
    is_show = models.BooleanField(verbose_name='显示', default=False)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = '博客评论'
        verbose_name_plural = "博客评论"
        ordering = ['-id']


# 网站公告
class Notice(models.Model):
    title = models.CharField(max_length=64)
    content = RichTextUploadingField(verbose_name='内容')
    keywords = models.CharField(max_length=32, verbose_name='关键字', null=True)
    description = models.CharField(max_length=64, verbose_name='描述', null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '网站公告'
        verbose_name_plural = "网站公告"
        ordering = ['-id']


# 关注
class Stars(models.Model):
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING, verbose_name='关注文章')
    user = models.ForeignKey(UserProfile, on_delete=models.DO_NOTHING, verbose_name='作者')

apps/blog/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/7/6 11:00
# @Author  : Hezq
# @Contact : Hezq168@gmail.com
# @File    : forms.py
# @Project : mysite
# @Software: PyCharm

from django import forms
from blog.models import Comments
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField

from django.forms import fields as Ffields
from django.forms import widgets as Fwidgets


# class CommentsForm(forms.Form):
#     comment = RichTextField()


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        # fields = '__all__'
        fields = ['content']
        widgets = {
            'content': Fwidgets.Textarea(attrs={'class': 'form-control', 'rows': "3", 'cols': "20"})
        }

apps/blog/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.views import View

from blog.models import Post, Tag, Comments, Type, Notice, Stars, UserProfile
from blog.forms import CommentsForm

import json


def index(request):
    # 获取所有文章
    if request.method == 'GET':
        _post = Post.objects.all()
        context = {'post': _post}
        return render(request, 'blog/index.html', context)
    else:
        pass


def post(request, id):
    if request.method == 'GET':
        # 获取文章内容
        post = Post.objects.filter(id=id).first()
        comment_form = CommentsForm()
        # 添加阅读数
        post.page_view += 1
        post.save()
        context = {'post': post, 'comment_form': comment_form}
        return render(request, 'blog/post.html', context)
    elif request.method == 'POST':
        comment_form = CommentsForm(request.POST)
        print(comment_form)
        if comment_form.is_valid():
            comm = request.POST['comment']
            id = int(request.POST['id'])
            post = Post.objects.get(id=id)
            # user = BlogUser.objects.get(id=1)
            obj = Comments(post=post, content=comm)
            try:
                obj.save()
            except:
                return HttpResponse('error')
            return HttpResponseRedirect('/blog/post/' + str(id))
        else:
            id = int(request.POST['id'])
            post = Post.objects.filter(id=id).first()
            comment_form = CommentsForm()

            context = {'post': post, 'comment_form': comment_form}

            return render(request, 'blog/post.html', context)
    else:
        pass


# 博客分类
class Category(View):
    # 获取分类
    def get(self, request, _id):
        _post = Post.objects.filter(type=_id)
        return render(request, 'blog/category.html', {'post': _post})


class TagView(View):
    # 获取标签
    def get(self, request, _id):
        _post = Post.objects.filter(tag=_id)
        _tag = Tag.objects.filter(id=_id).first()
        return render(request, 'blog/tag.html', {'post': _post, 'tag': _tag})


class NoticeView(View):
    # 网站公告
    def get(self, request, _id):
        _notice = Notice.objects.filter(id=_id).first()
        return render(request, 'blog/notice.html', {'notice': _notice})


class CommentView(View):
    """
    评论
    """

    @method_decorator(login_required)
    def post(self, request):
        code = request.POST.get('code', None)
        _id = int(request.POST.get('id', None))
        description = request.POST.get('description', None)
        msg = {'status': 'ok', 'data': '', 'error': ''}
        if code and description:
            check_code = request.session['CheckCode']
            if code.lower() == check_code:
                _post = Post.objects.get(id=_id)
                Comments.objects.create(content=description, post=_post)
                msg['data'] = '评论成功，待管理员审核通过后显示！'
                return HttpResponse(json.dumps(msg))
            else:
                msg['status'] = 'no'
                msg['error'] = '验证码不正确！'
        else:
            msg['status'] = 'no'
            msg['error'] = '评论或验证码不能为空！'

        return HttpResponse(json.dumps(msg))


class StarsView(View):
    """
    关注
    """
    @method_decorator(login_required)
    def post(self, request):
        post_id = request.POST.get('post_id', None)
        exiset_records = Stars.objects.filter(user=request.user, post=post_id)
        if exiset_records:
            # 如果记录已经存在，则表示用户取消关注
            exiset_records.delete()
            msg = {'status': 'ok', 'data': '关注取消！', 'error': ''}
        else:
            _post = Post.objects.get(id=post_id)
            Stars.objects.create(post=_post, user=request.user)
            msg = {'status': 'ok', 'data': '关注成功！', 'error': ''}
        return HttpResponse(json.dumps(msg))

templates/blog/category.html
{% extends 'base.html' %}

{% load custom_tag %}
{% block title %}{{ post.first.type.name }}{% endblock %}
{% block keywords %}
    <meta name="keywords" content="{{ post.first.type.keywords }}"/>
    <meta name="description" content="{{ post.first.type.description }}"/>
{% endblock %}
{% block content %}
    {% load staticfiles %}
    <!--内容-->
    <div id="content">
        <div class="container">
            <div class="row">
                <!--左边内容-->
                <div class="col-md-9">
                    <!--愽客文章-->
                    {% for post in post %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h2 class="panel-title">
                        <span class="category">
                            <a href="">{{ post.type }}</a><i class="fa fa-caret-right"></i>
                        </span>
                                    {{ post.title }}
                                </h2>
                            </div>
                            <div class="panel-body">
                                <div class="pull-left viewimg">
                                    <a href="">
                                        <img src="/media/{{ post.cover }}" alt=""/>
                                    </a>
                                </div>
                                <div class="preview">
                                    {{ post.content | safe }}
                                </div>
                                <div class="preem hidden-sm hidden-xs">
                                    <span><i class="fa fa-clock-o"></i> {{ post.created_time|date:"Y-m-d" }}</span>
                                    <span><i class="fa fa-eye"></i> {{ post.page_view }}阅读</span>
                                    <span><i class="fa fa-comment-o"></i><a
                                            href="{% url 'blog_post' id=post.id %}"> {{ post.comments_set.count }}评论</a></span>
                                    <span style="color: #f78585"><i class="fa fa-heart-o"></i> {% stars_count post.id %}喜欢</span>
                                    <span class="pull-right"><a href="{% url 'blog_post' id=post.id %}">阅读更多</a></span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!--右边内容-->
                {% include 'blog/right.html' %}
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/comment.html
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">评论内容:</h4>
            </div>
            <form action="#" method="post" id="add">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ post.id }}">

                <div class="modal-body">
                    <div class="form-group">
                        <label for="comment" class="control-label"></label>
                        <textarea name="description" id="description" class="form-control"/></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <label>验证码：</label>
                    <img src="{% url 'check_code' %}" alt="code">
                    <input type="text" name="code" id="code">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" id="comm" class="btn btn-primary">评论</button>
                    {% for k,v in comment_form.errors.items %}{{ v }}{% endfor %}{{ msg }}
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/blog/index.html
{% extends 'base.html' %}
{% load custom_tag %}

{% block title  %}我的博客{% endblock %}

{% block content %}
{% load staticfiles %}

<div id="content">
    <div class="container">
        <div class="row">
            <!--左边内容-->
            <div class="col-md-9">
                <!--愽客文章-->
                {% for post in post %}
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                        <span class="category">
                            <a href="{% url 'blog_category' _id=post.type.id %}">{{ post.type }}</a><i class="fa fa-caret-right"></i>
                        </span>
                            {{ post.title }}
                        </h2>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left viewimg">
                            <a href="">
                                <img src="/media/{{ post.cover }}" alt=""/>
                            </a>
                        </div>
                        <div class="preview">
                            {{ post.content | safe }}
                        </div>
                        <div class="preem hidden-sm hidden-xs">
                            <span><i class="fa fa-clock-o"></i> {{ post.created_time|date:"Y-m-d"}}</span>
                            <span><i class="fa fa-eye"></i> {{ post.page_view }}阅读</span>
                            <span><i class="fa fa-comment-o"></i><a href="{% url 'blog_post' id=post.id %}"> {{ post.comments_set.count }}评论</a></span>
                            <span style="color: #f78585"><i class="fa fa-heart-o"></i> {% stars_count post.id %}喜欢</span>
                            <span class="pull-right"><a href="{% url 'blog_post' id=post.id %}">阅读更多</a></span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!--右边内容-->
            {% include 'blog/right.html' %}
        </div>
    </div>
</div>
{% endblock %}

templates/blog/index1.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>首页</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="static/lib/bootstrap3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/base.css" />

    <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<h1>愽客首页</h1>
<div id="top">头部</div>
<nav id="nav">导航条</nav>
<div id="notice">公告</div>
<div id="content">
    <!--内部-->
</div>
<div id="footer">
    页脚
</div>
<script src="static/lib/jquery3.3.1/jquery.min.js"></script>
<script src="static/lib/bootstrap3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/blog/notice.html
{% extends 'base.html' %}


{% block title  %}公告{% endblock %}

{% block content %}
{% load staticfiles %}



<div id="content">
    <div class="container">
        <div class="row">
            <!--左边内容-->
            <div class="col-md-9">
                <!--愽客文章-->
                {% for post in post %}
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                        <span class="category">
                            <a href="{% url 'blog_category' _id=post.type.id %}">{{ post.type }}</a><i class="fa fa-caret-right"></i>
                        </span>
                            {{ post.title }}
                        </h2>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left viewimg">
                            <a href="">
                                <img src="/media/{{ post.cover }}" alt=""/>
                            </a>
                        </div>
                        <div class="preview">
                            {{ post.content | safe }}
                        </div>
                        <div class="preem hidden-sm hidden-xs">
                            <span><i class="fa fa-clock-o"></i> {{ post.created_time|date:"Y-m-d"}}</span>
                            <span><i class="fa fa-eye"></i> {{ post.page_view }}阅读</span>
                            <span><i class="fa fa-comment-o"></i><a href="{% url 'blog_post' id=post.id %}"> {{ post.comments_set.count }}评论</a></span>
                            <span style="color: #f78585"><i class="fa fa-heart-o"></i> {{ post.love }}喜欢</span>
                            <span class="pull-right"><a href="{% url 'blog_post' id=post.id %}">阅读更多</a></span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!--右边内容-->
            {% include 'blog/right.html' %}
        </div>
    </div>
</div>
{% endblock %}

templates/blog/post.html
{% extends 'base.html' %}
{% load custom_tag %}
{% block title %}{{ post.title }}{% endblock %}
{% block keywords %}
    <meta name="keywords" content="{{ post.keywords }}"/>
    <meta name="description" content="{{ post.description }}"/>
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <!--内容-->
    <div id="content">
        <div class="container">
            <div class="row">
                <!--左边内容-->
                <div class="col-md-9">
                    <!--愽客文章-->
                    {#                    {% for post in post %}#}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h2 class="panel-title">
                                <ul class="breadcrumb" style="margin-bottom: 0px;padding: 8px 0px;">
                                    <li>
                                        <a href="{% url 'blog_index' %}"><i class="fa fa-home"></i></a>
                                    </li>
                                    <li>
                                        <a href="{% url 'blog_category' _id=post.type.id %}">{{ post.type }}</a>
                                    </li>
                                    <li class="active">{{ post.title }}</li>
                                </ul>
                            </h2>
                            <h2 style="margin-top: 5px;">{{ post.title }}</h2>

                            <div class="preem hidden-sm hidden-xs">
                                <span><i class="fa fa-list-alt"></i><a href=""> {{ post.type }}</a></span>
                                <span><i class="fa fa-user"></i><a href=""> {{ post.author.first_name }}</a></span>
                                <span><i class="fa fa-clock-o"></i> {{ post.created_time }}</span>
                                <span><i class="fa fa-eye"></i> {{ post.page_view }}</span>
                                    <span><i class="fa fa-comment-o"></i><a
                                            href="{% url 'blog_post' id=post.id %}"> {{ post.comments_set.count }}评论</a></span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <article class="article-content">
                                {{ post.content|safe }}
                            </article>
                            <div class="like_share">
                                <button type="button" id='stars' class="btn btn-default" value="{{ post.id }}">
                                    <i class="fa fa-heart-o"></i>
                                    喜欢
                                    <span class="link-count">{% stars_count post.id %} </span></button>
                            </div>
                            <hr/>

                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h2 class="panel-title">
                                        <span>评论列表</span>
                                        <button class="btn btn-primary btn-sm pull-right comment"
                                                style="position: relative;top: -5px;" data-toggle="modal"
                                                data-target="#myModal">
                                            <i class="fa fa-check-square-o"></i> 评论
                                        </button>
                                        {% for k,v in comment_form.errors.items %}{{ v }}{% endfor %}{{ msg }}
                                    </h2>
                                </div>
                                {% for comm in post.comments_set.all %}
                                    {#                               判断评论是否显示#}
                                    {% if comm.is_show == 1 %}
                                        <div class="panel-body">
                                            <div class="pull-left pinglun-avatar">

                                                <p><img src="/media/{{ comm.blog_user.photo }}" alt="头像"/></p>

                                                <p>{{ comm.blog_user.nick_name }}</p>

                                            </div>
                                            <div class="pinglun-body">
                                                <h3>{{ comm.author }}
                                                    <span class="pull-right">{{ comm.created_time }}</span>
                                                </h3>

                                                <div class="pinglun-text">
                                                    {{ comm.content|safe }}
                                                </div>
                                                {% if request.user.is_staff %}
                                                    <div class="pinglun-bottom pull-right"><a href="">回复</a></div>
                                                {% endif %}
                                            </div>

                                        </div>
                                        <hr style="margin:  5px 0;"/>
                                    {% endif %}
                                {% empty %}
                                    <div class="text-center">
                                        <p>---暂无评论---</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    {#                    {% endfor %}#}
                </div>
                <!--右边内容-->
                {% include 'blog/right.html' %}
            </div>
        </div>
    </div>
    {#  添加评论模态状态#}
    {% if request.user.is_authenticated %}
        {% include 'blog/comment.html' %}
    {% endif %}
{% endblock %}

{% block jscript %}
    {% if request.user.is_authenticated %}
        <script src="{% static 'lib/ckeditor/ckeditor/ckeditor.js' %}"></script>
        <script type="text/javascript">
            CKEDITOR.replace('description',
                    {
                        toolbar: [
                            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
                            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
                            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
                            ['Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor', 'CodeSnippet', 'Maximize', 'ShowBlocks', '-'],
                        ]
                    }
            );
        </script>
        <script>

            $('#comm').click(function () {
                for (instance in CKEDITOR.instances) {
                    CKEDITOR.instances[instance].updateElement();
                }
                if ($('#code').val().length != 0 && $('#description').val().length != 0) {
                    $.ajax({
                        url: '{% url 'blog_comment' %}',
                        type: 'POST',
                        data: $('#add').serialize(),
                        dataType: 'JSON',
                        success: function (rep) {
                            console.log(rep);
                            if (rep.status == 'ok') {
                                alert(rep.data);
                                location.reload();
                            } else {
                                alert(rep.error);
                            }
                        }
                    })
                } else {
                    alert('验证码不能为空！');
                }
            });
        </script>
    {% endif %}
    <script>
        {% if request.user.is_authenticated %}

        {% else %}
            $('.comment').click(function () {
                window.location.href = "/users/login?next={{ request.path }}";
            })
        {% endif %}


        $('#stars').click(function () {
            {% if request.user.is_authenticated %}
                var post_id = $(this).val();
                $.ajaxSetup({
                    data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
                });
                $.ajax({
                    url: '{% url 'blog_stars' %}',
                    type: 'POST',
                    data: {'post_id': post_id},
                    dataType: 'JSON',
                    success: function (rep) {
                        console.log(rep);
                        if (rep.status == 'ok') {
                            alert(rep.data);
                            location.reload();
                        } else {
                            alert(rep.error);
                        }
                    }
                })
            {% else %}
                window.location.href = "/users/login?next={{ request.path }}";
            {% endif %}

        });

    </script>

{% endblock %}

templates/blog/right.html
{% load custom_tag %}
{% post_tag as tag_list %}
{% post_type as type_list %}


<div class="col-md-3  hidden-sm hidden-xs">
    <!--文章分类-->
    <div class="panel panel-default subblock">
        <div class="panel-heading">
            <h3 class="panel-title "><i class="fa fa-align-justify"></i> 文章分类</h3>
        </div>
        <ul class="list-group">
            {% for type in type_list %}
                <li class="list-group-item">
                                <span class="badge">
                                    {{ type.post_set.count }}
                                </span>
                    <a href="{% url 'blog_category' _id=type.id %}">{{ type.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!--标签-->
    <div class="panel panel-default subblock">
        <div class="panel-heading">
            <h3 class="panel-title "><i class="fa fa-align-justify"></i> 标签</h3>
        </div>
        <div class="panel-body">
            <ul class="tag_cloud">
                {% for tag in tag_list %}
                    <a href="{% url 'blog_tag' _id=tag.id %}" title="{{ tag.post_set.count }}个话题" class="pull-left">
                        {{ tag.name }}&nbsp;&nbsp;&nbsp;({{ tag.post_set.count }})
                    </a>
                {% empty %}
                    暂无标签！
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

templates/blog/tag.html
{% extends 'base.html' %}


{% block title %}{{ tag.name }}{% endblock %}

{% block keywords %}
    <meta name="keywords" content="{{ tag.keywords }}"/>
    <meta name="description" content="{{ tag.description }}"/>
{% endblock %}

{% block content %}
{% load staticfiles %}
<!--内容-->
<div id="content">
    <div class="container">
        <div class="row">
            <!--左边内容-->
            <div class="col-md-9">
                <!--愽客文章-->
                {% for post in post %}
                    <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                        <span class="category">
                            <a href="">{{ post.type }}</a><i class="fa fa-caret-right"></i>
                        </span>
                            {{ post.title }}
                        </h2>
                    </div>
                    <div class="panel-body">
                        <div class="pull-left viewimg">
                            <a href="">
                                <img src="/media/{{ post.cover }}" alt=""/>
                            </a>
                        </div>
                        <div class="preview">
                            {{ post.content | safe }}
                        </div>
                        <div class="preem hidden-sm hidden-xs">
                            <span><i class="fa fa-clock-o"></i> {{ post.created_time|date:"Y-m-d"}}</span>
                            <span><i class="fa fa-eye"></i> {{ post.page_view }}阅读</span>
                            <span><i class="fa fa-comment-o"></i><a href="{% url 'blog_post' id=post.id %}"> {{ post.comments_set.count }}评论</a></span>
                            <span style="color: #f78585"><i class="fa fa-heart-o"></i> {{ post.love }}喜欢</span>
                            <span class="pull-right"><a href="{% url 'blog_post' id=post.id %}">阅读更多</a></span>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!--右边内容-->
            {% include 'blog/right.html' %}
        </div>
    </div>
</div>

{% endblock %}